import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import './globals.css'
import ThemeRegistry from './ThemeRegistry'
import ResponsiveAppBar from '../components/header/header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

export default function RootLayout(props:any) {
  const { children } = props;
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: 'mui' }}>
        <ResponsiveAppBar></ResponsiveAppBar>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}